name: app_fortress
description: Production-grade multi-layer app security - SSL Pinning, Anti-Debug, Code Obfuscation, Play Integrity (Android), App Attest (iOS), Root/Jailbreak detection, and Native C protection layer.
version: 1.0.1
homepage: https://github.com/girija870/app_fortress
repository: https://github.com/girija870/app_fortress
issue_tracker: https://github.com/girija870/app_fortress/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.app.fortress
        pluginClass: AppFortressPlugin
      ios:
        pluginClass: AppFortressPlugin

topics:
  - security
  - ssl-pinning
  - root-detection
  - play-integrity
  - anti-tampering
